version: '3'

services:
  hadoop:
    image: sequenceiq/hadoop-docker:2.6.0
    container_name: hadoop-cluster
    hostname: single.cluster.hadoop.dev
    working_dir: /usr/local/hadoop
    volumes:
      - ./scripts:/usr/local/hadoop/scripts 
      - ./etc:/usr/local/hadoop/etc
    ports:
      - 8030:8030
      - 8031:8031
      - 8032:8032
      - 8033:8033
      - 40961:40961
      - 50020:50020
      - 8040:8040
      - 9000:9000
      - 8042:8042
      - 50090:50090
      - 50070:50070
      - 8088:8088
      - 13562:13562
      - 50010:50010
      - 50075:50075
    #depends_on:
    #  - ss5
  #ss5:
    #image: dijedodol/simple-socks5-server
    #container_name: socks5
    #ports:
    #  - 1080:1080  
    #restart: always

        
